name       : fahviewer
version    : 7.5
release    : 1
source     :
    - https://download.foldingathome.org/releases/public/release/fahviewer/debian-stable-64bit/v7.5/fahviewer_7.5.1_amd64.deb : c87d331a35fc68d04427996aef05b275ca69dab3bef4087efaaf5e27e95d7b29
license    : N/A
summary    : Folding @ Home Viewer
description: |
    Folding @ Home Viewer
builddeps  :
    - pkgconfig(libglvnd)
    - pkgconfig(glu)
    - pkgconfig(freeglut)
install    : |
    cp $sources/fahviewer_7.5.1_amd64.deb .
    install -d $installdir
    ar xf fahviewer_7.5.1_amd64.deb
    tar xf data.tar.xz -C $installdir
